const app = document.getElementById('app');
const toast = document.querySelector('.toast');
let lang = localStorage.getItem('acx-lang') || 'en';

const copy = {
  en: {
    nav: ['Services','Industries','Studios','Work','For Partners','About'],
    footerLead: 'Making content travel further.', footerQuestion: 'Have a project in mind?', footerExplore: 'Explore', footerConnect: 'Connect', footerFocus: 'Focus', footerBase: 'Base', footerAvailable: 'Available for selected projects',
    start: 'Start a project', partner: 'Become a production partner', view: 'Explore', talk: "Let's talk", request: 'Request a quote', learn: 'Learn more', available: 'Available for selected projects',
    home: {
      eyebrow: 'Global media localization & production', title: 'Make content <span class="accent">travel</span> <span class="soft">further.</span>', lead: 'We help content owners, producers, localization companies and brands adapt, produce and deliver media for new languages, markets and audiences.', meta: 'Built from real production experience', cardLabel: 'LIVE PRODUCTION PULSE', cardStatus: 'SYSTEM READY', cardFootA: 'Current workflow', cardFootB: 'Multi-stage delivery', stats: [['3','equipped studios'],['01','production partner'],['∞','ways to scale'],['24/7','remote ready']], strip: ['Content owners','Localization teams','Producers','Brands'], sectionEyebrow: 'The ACX system', sectionTitle: 'One partner. Multiple production capabilities.', sectionText: 'From one production step to a complete delivery workflow, we build the right production model for your content, language, volume and deadlines.', processEyebrow: 'How we work', processTitle: 'From content to audience.', processText: 'A clear, documented workflow keeps quality high and every handoff visible.', process: [['01','Brief & assets','We align on scope, source files and delivery requirements.'],['02','Build','Editorial, language, voice and audio production move together.'],['03','QC','Internal review, corrections and final validation protect the master.'],['04','Deliver','Organized, secure and ready for the next stage of your workflow.']], ctaTitle: 'Ready to make your content travel?', ctaText: 'Tell us what you are building. We will help define the right workflow.'
    },
    services: { eyebrow:'Capabilities', title:'The production layer between content and audience.', lead:'Localization, dubbing, subtitling, voice, accessibility, audio post-production, media QC and delivery — connected in one flexible workflow.', introEyebrow:'Our services', introTitle:'Production expertise, not just a menu of deliverables.', introText:'ACX Media can own one stage of your workflow or coordinate the full journey from source content to delivery-ready assets.', rows:[['01','Localization','Transcription, translation, adaptation and subtitle production for new markets.',['Transcription','Subtitling','SDH / CC']],['02','Dubbing','Adapted dialogue, casting, recording, synchronization, mixing and QC.',['Casting','Recording','Mixing']],['03','Voice','Voice-over, narration, documentary, corporate, e-learning, advertising and TTS workflows.',['Voice-over','Narration','TTS']],['04','Accessibility','Audio description scriptwriting, voice, TTS, mixing and accessibility QC.',['Audio description','AD voice','AD QC']],['05','Audio post-production','Dialogue cleaning, voice editing, sound design support, mastering and stems.',['Editing','Mixing','M&E']],['06','Media QC & delivery','Linguistic, subtitle, audio, technical and final package validation.',['Linguistic QC','Technical QC','Delivery']]], bottomTitle:'Your workflow. Our production discipline.', bottomText:'Technical specifications are reviewed project by project. We only commit to formats supported by a validated production workflow.' },
    industries: { eyebrow:'Industries', title:'Built for content that needs to travel.', lead:'Different content types require different workflows. We adapt our production model to the audience, language, volume and delivery requirements of each project.', introEyebrow:'Who we support', introTitle:'Content-led businesses with somewhere to go.', introText:'From a single film extract to a recurring multilingual pipeline, ACX Media brings structure, flexibility and quality control to the production layer.', industries:[['Media & Entertainment','Films, series, documentaries and entertainment content.','↗'],['Streaming & OTT','Recurring content volumes, accessibility and multilingual versions.','↗'],['Localization Companies','White-label capacity for agencies managing multiple clients and languages.','↗'],['Production Companies','Voice, subtitling, accessibility and localized versions for original content.','↗'],['Post-Production','Additional audio, QC and delivery capacity when internal resources peak.','↗'],['E-learning','Multilingual narration, adaptation, subtitles and accessible learning content.','↗'],['Corporate','Internal communications, training and multilingual brand content.','↗'],['Advertising & Digital','Voice, adaptation, audio and localization for campaigns and digital media.','↗']] },
    studios: { eyebrow:'Studios', title:'Physical capacity. Remote-ready production.', lead:'Three equipped studios supported by an experienced team across voice, audio workflows, mixing, validation and delivery.', studioIntro:'Our studios are part of a broader production system. The value is not only the equipment, but also the people, workflow documentation and quality controls behind every delivery.', studios:[['01','Voice Lab','A focused space for voice-over, narration, audio description and dialogue recording.',['Voice recording','Remote direction','AD / VO']],['02','Mix Suite','A controlled environment for voice editing, audio assembly and mix preparation.',['Editing','Mixing','Mastering']],['03','QC Desk','A production and review layer for linguistic, audio, technical and final checks.',['Linguistic QC','Audio QC','Delivery']]], note:'Studio availability, configurations and technical deliverables are confirmed according to project requirements and applicable usage authorizations.' },
    languages: { eyebrow:'Languages', title:'Languages are part of the workflow — not an afterthought.', lead:'We combine a core francophone production capability with a flexible network of language professionals, voice talents and reviewers.', core:'Core capability', coreTitle:'French-first. International by design.', copy:'Our language model is built around qualified teams, clear review stages and project-by-project validation — not unsupported language lists.', pills:['French','English','Arabic','Spanish','European languages','Qualified partner network'], note:'Language availability depends on content type, volume, timeline, specialization and validation resources. We define the right team for each brief.' },
    work: { eyebrow:'Work / demos', title:'See how content becomes audience-ready.', lead:'Our demos showcase the production stages, formats and workflows ACX Media can support. Confidential client work stays confidential.', workCards:[['Featured workflow','Audio description','Editorial precision meets voice, timing and final mix.'],['Localization sample','Subtitling & SDH','Meaning, timing and accessibility aligned for a new audience.'],['Voice production','Corporate voice-over','A clear voice, a clean edit and delivery-ready audio.']], demos:[['01','Film / series subtitling','Subtitle timing · Linguistic adaptation'],['02','Audio description','Script · Voice · Mix'],['03','Corporate voice-over','Narration · Cleanup · Master'],['04','Dubbing extract','Adaptation · Recording · Sync'],['05','Multilingual e-learning','Voice · Subtitles · Languages']] },
    partners: { eyebrow:'For partners', title:'You sell. <span>We produce.</span>', lead:'ACX Media gives localization companies, agencies, studios and post-production businesses access to flexible production capacity behind the scenes.', partnerIntro:'Your clients need quality, speed and consistency. Your internal team may not always have the capacity to deliver every stage of every project. We can operate as an extension of your production team — under your workflow, your specifications and, when appropriate, your brand.', models:[['01','Overflow production','Additional capacity for peaks, deadlines and unexpected volumes.'],['02','Recurring production','Ongoing support for regular content pipelines and monthly volumes.'],['03','Dedicated team','A structured team assigned to a recurring client or language program.'],['04','Selected workflow stages','Subtitles, voice, accessibility, mixing, QC or delivery — without taking over everything.']], cta:'Discuss a production partnership' },
    about: { eyebrow:'About ACX', title:'Built from production experience. Designed for global content.', lead:'ACX Media is a media localization and production company built around practical experience in accessibility, audio, voice, editorial adaptation, quality control and delivery.', p1:'The company’s roots are in audio description production for Québec and Canadian audiovisual content. This experience created a strong foundation in structured workflows, editorial precision, synchronization, voice production, audio preparation, studio validation and deadline management.', p2:'ACX Media now brings this production culture to a broader international offer covering localization, dubbing, subtitling, voice, audio post-production, accessibility, media QC and delivery.', statement:'Audio description was not replaced. It became one of the foundations of ACX Media.', values:[['Quality','We document, review and validate the work.'],['Reliability','We respect the workflow, timeline and confidentiality of each project.'],['Flexibility','We adapt the production model to the client’s needs and volumes.'],['Partnership','We aim to become a trusted extension of the client’s team.']] },
    contact: { eyebrow:'Contact', title:'Let’s talk about your next production.', lead:'Tell us about your content, target markets, languages, volumes and delivery requirements. We will help identify the right production workflow.', details:[['Base','Casablanca, Morocco'],['Availability','International remote production'],['Email','media@acx.ma'],['Response','Usually within 1–2 business days']], formTitle:'Start a conversation', labels:['Full name','Company','Work email','Project type','Message'], placeholders:['Your name','Your company','you@company.com','Select a project type','Tell us what you are building…'], select:['Localization','Subtitling','Dubbing','Voice-over','Audio description','Audio post-production','Media QC','White-label partnership'], formNote:'By sending this form, you agree that ACX Media may use your information to respond to your request.' }
  },
  fr: {
    nav: ['Services','Secteurs','Studios','Réalisations','Partenaires','À propos'],
    footerLead: 'Faire voyager les contenus plus loin.', footerQuestion: 'Un projet en tête ?', footerExplore: 'Explorer', footerConnect: 'Contact', footerFocus: 'Expertise', footerBase: 'Base', footerAvailable: 'Disponible pour certains projets',
    start: 'Démarrer un projet', partner: 'Devenir partenaire de production', view: 'Explorer', talk: 'Parlons-en', request: 'Demander un devis', learn: 'En savoir plus', available: 'Disponible pour certains projets',
    home: { eyebrow:'Localisation et production média internationales', title:'Faites <span class="accent">voyager</span> vos contenus <span class="soft">plus loin.</span>', lead:'Nous aidons les propriétaires de contenus, producteurs, sociétés de localisation et marques à adapter, produire et livrer leurs médias pour de nouvelles langues, de nouveaux marchés et de nouveaux publics.', meta:'Une expertise issue de la production réelle', cardLabel:'PULSE DE PRODUCTION', cardStatus:'SYSTÈME PRÊT', cardFootA:'Workflow actif', cardFootB:'Livraison multi-étapes', stats:[['3','studios équipés'],['01','partenaire de production'],['∞','façons de monter en capacité'],['24/7','prêt pour le remote']], strip:['Propriétaires de contenus','Équipes de localisation','Producteurs','Marques'], sectionEyebrow:'Le système ACX', sectionTitle:'Un partenaire. Plusieurs capacités de production.', sectionText:'D’une seule étape à un workflow complet, nous construisons le bon modèle de production selon vos contenus, langues, volumes et délais.', processEyebrow:'Notre méthode', processTitle:'Du contenu au public.', processText:'Un workflow clair et documenté maintient la qualité et rend chaque transmission visible.', process:[['01','Brief et éléments','Nous alignons le périmètre, les fichiers sources et les exigences de livraison.'],['02','Production','Éditorial, langues, voix et audio avancent ensemble.'],['03','Contrôle qualité','Vérification interne, corrections et validation finale protègent le master.'],['04','Livraison','Des fichiers organisés, sécurisés et prêts pour la suite du workflow.']], ctaTitle:'Prêt à faire voyager vos contenus ?', ctaText:'Décrivez-nous votre projet. Nous vous aiderons à définir le bon workflow.' },
    services: { eyebrow:'Capacités', title:'Le lien de production entre le contenu et son public.', lead:'Localisation, doublage, sous-titrage, voix, accessibilité, postproduction audio, contrôle qualité et livraison — réunis dans un workflow flexible.', introEyebrow:'Nos services', introTitle:'Une expertise de production, pas seulement un catalogue.', introText:'ACX Media peut prendre en charge une étape de votre workflow ou coordonner l’ensemble du parcours, du contenu source aux éléments prêts à livrer.', rows:[['01','Localisation','Transcription, traduction, adaptation et sous-titrage pour de nouveaux marchés.',['Transcription','Sous-titrage','SDH / CC']],['02','Doublage','Adaptation, casting, enregistrement, synchronisation, mixage et QC.',['Casting','Enregistrement','Mixage']],['03','Voix','Voice-over, narration, documentaire, corporate, e-learning, publicité et TTS.',['Voice-over','Narration','TTS']],['04','Accessibilité','Écriture AD, voix, TTS, mixage et contrôle qualité accessibilité.',['Audiodescription','Voix AD','QC AD']],['05','Postproduction audio','Nettoyage des dialogues, édition, mastering et préparation des stems.',['Édition','Mixage','M&E']],['06','Media QC et livraison','Contrôle linguistique, sous-titres, audio, technique et package final.',['QC linguistique','QC technique','Livraison']]], bottomTitle:'Votre workflow. Notre discipline de production.', bottomText:'Les spécifications techniques sont étudiées au cas par cas. Nous nous engageons uniquement sur les formats pris en charge par un workflow validé.' },
    industries: { eyebrow:'Secteurs', title:'Pour les contenus qui doivent voyager.', lead:'Chaque type de contenu appelle un workflow spécifique. Nous adaptons notre modèle de production à l’audience, aux langues, aux volumes et aux exigences de livraison.', introEyebrow:'Nos clients', introTitle:'Des entreprises dont le contenu a une destination.', introText:'D’un extrait de film à un pipeline multilingue récurrent, ACX Media apporte structure, flexibilité et contrôle qualité à la production.', industries:[['Media & Entertainment','Films, séries, documentaires et contenus de divertissement.','↗'],['Streaming & OTT','Volumes récurrents, accessibilité et versions multilingues.','↗'],['Sociétés de localisation','Capacité white-label pour agences gérant plusieurs clients et langues.','↗'],['Sociétés de production','Voix, sous-titres, accessibilité et versions localisées.','↗'],['Postproduction','Capacité audio, QC et livraison lorsque les volumes augmentent.','↗'],['E-learning','Narration multilingue, adaptation, sous-titres et contenus accessibles.','↗'],['Corporate','Communication interne, formation et contenus de marque multilingues.','↗'],['Publicité et digital','Voix, adaptation, audio et localisation pour campagnes et médias digitaux.','↗']] },
    studios: { eyebrow:'Studios', title:'Une capacité physique. Une production prête pour le remote.', lead:'Trois studios équipés, soutenus par une équipe expérimentée en voix, workflows audio, mixage, validation et livraison.', studioIntro:'Nos studios s’inscrivent dans un système de production plus large. La valeur ne réside pas uniquement dans l’équipement, mais aussi dans les équipes, la documentation et les contrôles qualité.', studios:[['01','Voice Lab','Un espace dédié à la voix-off, narration, audiodescription et enregistrement de dialogues.',['Enregistrement voix','Direction à distance','AD / VO']],['02','Mix Suite','Un environnement contrôlé pour l’édition voix, l’assemblage audio et la préparation du mix.',['Édition','Mixage','Mastering']],['03','QC Desk','Une couche de production et de revue pour les contrôles linguistiques, audio, techniques et finaux.',['QC linguistique','QC audio','Livraison']]], note:'La disponibilité des studios, les configurations et les livrables techniques sont confirmés selon le projet et les autorisations d’utilisation applicables.' },
    languages: { eyebrow:'Langues', title:'La langue fait partie du workflow — jamais après coup.', lead:'Nous combinons une capacité de production francophone avec un réseau flexible de professionnels de la langue, de comédiens et de réviseurs.', core:'Capacité centrale', coreTitle:'Une base francophone. Une ambition internationale.', copy:'Notre modèle linguistique repose sur des équipes qualifiées, des étapes de revue claires et une validation projet par projet — pas sur des listes de langues non vérifiées.', pills:['Français','Anglais','Arabe','Espagnol','Langues européennes','Réseau de partenaires qualifiés'], note:'La disponibilité dépend du type de contenu, du volume, du délai, de la spécialisation et des ressources de validation. Nous définissons la bonne équipe pour chaque brief.' },
    work: { eyebrow:'Réalisations / démos', title:'Voir comment un contenu devient prêt pour son public.', lead:'Nos démos montrent les étapes, formats et workflows qu’ACX Media peut prendre en charge. Les projets confidentiels restent confidentiels.', workCards:[['Workflow vedette','Audiodescription','La précision éditoriale rencontre la voix, le timing et le mix final.'],['Exemple de localisation','Sous-titrage et SDH','Sens, timing et accessibilité alignés pour un nouveau public.'],['Production voix','Voice-over corporate','Une voix claire, une édition propre et un audio prêt à livrer.']], demos:[['01','Sous-titrage film / série','Timing · Adaptation linguistique'],['02','Audiodescription','Script · Voix · Mix'],['03','Voice-over corporate','Narration · Nettoyage · Master'],['04','Extrait de doublage','Adaptation · Enregistrement · Synchro'],['05','E-learning multilingue','Voix · Sous-titres · Langues']] },
    partners: { eyebrow:'Pour les partenaires', title:'Vous vendez. <span>Nous produisons.</span>', lead:'ACX Media donne aux sociétés de localisation, agences, studios et entreprises de postproduction une capacité de production flexible, en coulisses.', partnerIntro:'Vos clients attendent qualité, vitesse et régularité. Vos équipes internes ne peuvent pas toujours prendre en charge chaque étape de chaque projet. Nous pouvons devenir une extension de votre production — selon vos process, vos spécifications et, lorsque c’est pertinent, sous votre marque.', models:[['01','Production de débordement','Une capacité supplémentaire pour les pics, délais courts et volumes imprévus.'],['02','Production récurrente','Un soutien continu pour vos pipelines réguliers et volumes mensuels.'],['03','Équipe dédiée','Une équipe structurée pour un client, un contenu ou un programme linguistique.'],['04','Étapes ciblées','Sous-titres, voix, accessibilité, mixage, QC ou livraison — sans reprendre tout le projet.']], cta:'Discuter d’un partenariat' },
    about: { eyebrow:'À propos d’ACX', title:'Issue de la production. Pensée pour les contenus internationaux.', lead:'ACX Media est une entreprise de localisation et de production média fondée sur une expérience concrète en accessibilité, audio, voix, adaptation éditoriale, contrôle qualité et livraison.', p1:'L’activité trouve ses racines dans la production d’audiodescription pour des contenus audiovisuels québécois et canadiens. Cette expérience a construit une base solide en workflows structurés, précision éditoriale, synchronisation, production de voix, préparation audio, validation studio et gestion des délais.', p2:'ACX Media élargit aujourd’hui cette culture de production à une offre internationale couvrant la localisation, le doublage, le sous-titrage, la voix, la postproduction audio, l’accessibilité, le media QC et la livraison.', statement:'L’audiodescription n’a pas été remplacée. Elle est devenue l’un des fondements d’ACX Media.', values:[['Qualité','Nous documentons, contrôlons et validons le travail.'],['Fiabilité','Nous respectons le workflow, les délais et la confidentialité.'],['Flexibilité','Nous adaptons le modèle de production aux besoins et volumes.'],['Partenariat','Nous voulons devenir une extension de confiance de vos équipes.']] },
    contact: { eyebrow:'Contact', title:'Parlons de votre prochaine production.', lead:'Décrivez-nous vos contenus, marchés cibles, langues, volumes et exigences de livraison. Nous vous aiderons à définir le bon workflow.', details:[['Base','Casablanca, Maroc'],['Disponibilité','Production internationale à distance'],['Email','media@acx.ma'],['Réponse','Généralement sous 1 à 2 jours ouvrés']], formTitle:'Démarrer une conversation', labels:['Nom complet','Entreprise','Email professionnel','Type de projet','Message'], placeholders:['Votre nom','Votre entreprise','vous@entreprise.com','Sélectionner un type de projet','Décrivez-nous votre projet…'], select:['Localisation','Sous-titrage','Doublage','Voice-over','Audiodescription','Postproduction audio','Media QC','Partenariat white-label'], formNote:'En envoyant ce formulaire, vous acceptez qu’ACX Media utilise vos informations pour répondre à votre demande.' }
  }
};

const waveBars = Array.from({length: 44}, (_, i) => `<i style="height:${18 + ((i * 17) % 63)}px;animation-delay:${(i % 9) * -.11}s"></i>`).join('');
const serviceIcons = ['✦','◌','◒','◈','⌁','✓'];

function t(key) { return copy[lang][key] ?? key; }
function c(page) { return copy[lang][page]; }
function routeName() { const raw = location.hash.replace('#','').split('?')[0]; return raw && copy.en[raw] ? raw : 'home'; }
function link(route, text, cls='') { return `<a class="${cls}" href="#${route}" data-route="${route}">${text}</a>`; }

function home() { const p=c('home'); return `<div class="page home-page"><section class="hero"><div class="hero-copy"><div class="eyebrow">${p.eyebrow}</div><h1 class="display">${p.title}</h1><p class="lead">${p.lead}</p><div class="hero-buttons"><a class="button button-primary" href="#contact" data-route="contact">${t('start')} <span>↗</span></a><a class="button button-outline" href="#services" data-route="services">${t('view')} <span>↗</span></a></div><div class="meta-line"><span></span>${p.meta}</div></div><div class="hero-art"><div class="hero-orbit"><span class="orbit-dot"></span><span class="orbit-dot purple"></span><span class="orbit-dot blue"></span></div><div class="pulse-card"><div class="pulse-head"><div class="pulse-label">${p.cardLabel}</div><div class="pulse-status"><i></i>${p.cardStatus}</div></div><div class="waveform">${waveBars}</div><div class="pulse-foot"><span>${p.cardFootA}<strong> · ACX-001</strong></span><span>${p.cardFootB}</span></div></div><span class="floating-tag tag-one">Localization</span><span class="floating-tag tag-two">Audio + QC</span><span class="floating-tag tag-three">Remote ready</span></div></section><div class="stat-strip">${p.stats.map(s=>`<div class="stat"><strong>${s[0]}</strong><span>${s[1]}</span></div>`).join('')}</div><div class="logo-strip">${p.strip.map(s=>`<span>${s}</span>`).join('')}</div><section class="section"><div class="section-head"><div><div class="eyebrow">${p.sectionEyebrow}</div><h2>${p.sectionTitle}</h2></div><p>${p.sectionText}</p></div><div class="card-grid">${serviceCards()}</div></section><section class="dark-band"><div class="process"><div><div class="eyebrow">${p.processEyebrow}</div><h2>${p.processTitle}</h2><p class="process-intro">${p.processText}</p></div><div class="process-list">${p.process.map(x=>`<div class="process-item"><span class="process-num">${x[0]}</span><div><strong>${x[1]}</strong><p>${x[2]}</p></div><span class="process-arrow">↗</span></div>`).join('')}</div></div></section><section class="section compact"><div class="cta-panel"><div><h2>${p.ctaTitle}</h2><p>${p.ctaText}</p></div><a class="button" href="#contact" data-route="contact">${t('start')} <span>↗</span></a></div></section></div>`; }
function serviceCards() { const p=c('services'); const cards=p.rows; return cards.map((row,i)=>`<a class="service-card" href="#services" data-route="services"><span class="card-number">${row[0]}</span><span class="card-icon">${serviceIcons[i]}</span><h3>${row[1]}</h3><p>${row[2]}</p><span class="card-link">${t('learn')} <span>↗</span></span></a>`).join(''); }
function pageHero(p, index) { return `<section class="page-hero"><div><div class="eyebrow">${p.eyebrow}</div><h1 class="page-title">${p.title}</h1><p class="lead">${p.lead}</p></div><div class="hero-index"><strong>${index}</strong><span>ACX / 2026</span></div></section>`; }
function services() { const p=c('services'); return `<div class="page">${pageHero(p,'01')}<section class="section"><div class="section-head"><div><div class="eyebrow">${p.introEyebrow}</div><h2>${p.introTitle}</h2></div><p>${p.introText}</p></div><div class="service-list">${p.rows.map((r,i)=>`<div class="service-row"><span class="row-number">${r[0]}</span><h3>${r[1]}</h3><p>${r[2]}</p><div class="row-tags">${r[3].map(x=>`<span class="pill">${x}</span>`).join('')}</div><span class="row-arrow">↗</span></div>`).join('')}</div></section><section class="section compact"><div class="cta-panel"><div><h2>${p.bottomTitle}</h2><p>${p.bottomText}</p></div><a class="button" href="#contact" data-route="contact">${t('request')} <span>↗</span></a></div></section></div>`; }
function industries() { const p=c('industries'); return `<div class="page">${pageHero(p,'02')}<section class="section"><div class="industry-layout"><div class="industry-intro"><div class="eyebrow">${p.introEyebrow}</div><h2>${p.introTitle}</h2><p>${p.introText}</p></div><div class="industry-list">${p.industries.map(x=>`<a class="industry-card" href="#contact" data-route="contact"><strong>${x[0]}</strong><p>${x[1]}</p><em>${x[2]}</em></a>`).join('')}</div></div></section><section class="section compact"><div class="metric-grid"><div class="metric-card"><strong>01</strong><span>Flexible production partner</span></div><div class="metric-card"><strong>03</strong><span>Equipped studios</span></div><div class="metric-card"><strong>∞</strong><span>Ways to build capacity</span></div></div></section></div>`; }
function studios() { const p=c('studios'); return `<div class="page">${pageHero(p,'03')}<section class="section"><div class="section-head"><div><div class="eyebrow">${p.eyebrow}</div><h2>${p.studioIntro}</h2></div><p>${p.lead}</p></div><div class="studio-grid">${p.studios.map((x,i)=>`<div class="studio-card"><div class="studio-visual"><span class="circle"></span><span class="cross"></span></div><h3>${x[0]} · ${x[1]}</h3><p>${x[2]}</p><div class="studio-specs">${x[3].map(y=>`<span class="pill">${y}</span>`).join('')}</div></div>`).join('')}</div><div class="studio-note"><strong>Workflow note.</strong> ${p.note}</div></section><section class="section compact"><div class="cta-panel"><div><h2>Build your next workflow with ACX.</h2><p>Tell us what needs to be recorded, edited, mixed or validated.</p></div><a class="button" href="#contact" data-route="contact">${t('talk')} <span>↗</span></a></div></section></div>`; }
function languages() { const p=c('languages'); return `<div class="page">${pageHero(p,'04')}<section class="section"><div class="language-layout"><div class="language-orb"><div class="core-word"><strong>ACX</strong><span>${p.core}</span></div><span class="lang-node node-fr"><b>FR</b> Français</span><span class="lang-node node-en"><b>EN</b> English</span><span class="lang-node node-ar"><b>AR</b> العربية</span><span class="lang-node node-es"><b>ES</b> Español</span></div><div class="language-copy"><div class="eyebrow">${p.core}</div><h2>${p.coreTitle}</h2><p>${p.copy}</p><div class="pill-list">${p.pills.map(x=>`<span class="pill">${x}</span>`).join('')}</div><div class="network-note">${p.note}</div></div></div></section><section class="section compact"><div class="cta-panel"><div><h2>Have a language brief?</h2><p>We will validate the right production team, review stages and delivery path for your project.</p></div><a class="button" href="#contact" data-route="contact">${t('talk')} <span>↗</span></a></div></section></div>`; }
function work() { const p=c('work'); return `<div class="page">${pageHero(p,'05')}<section class="section"><div class="work-grid">${p.workCards.map((x,i)=>`<div class="work-card ${i===0?'big':''}"><div class="work-visual"><div class="work-lines"></div></div><button class="play" type="button" data-toast="Demo preview coming soon">▶</button><span class="work-type">${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></div>`).join('')}</div><div class="demo-list">${p.demos.map(x=>`<div class="demo-row"><span class="demo-no">${x[0]}</span><strong>${x[1]}</strong><span>${x[2]}</span><button type="button" data-toast="Demo preview coming soon">↗</button></div>`).join('')}</div></section><section class="section compact"><div class="cta-panel"><div><h2>Need a custom demo?</h2><p>Share a short brief and we can shape the right proof of capability.</p></div><a class="button" href="#contact" data-route="contact">${t('request')} <span>↗</span></a></div></section></div>`; }
function partners() { const p=c('partners'); return `<div class="page"><section class="partner-hero"><div class="eyebrow">${p.eyebrow}</div><h1>${p.title}</h1><p>${p.lead}</p><div class="hero-buttons"><a class="button button-primary" href="#contact" data-route="contact">${t('partner')} <span>↗</span></a></div></section><section class="section"><div class="section-head"><div><div class="eyebrow">Production models</div><h2>Capacity that fits behind your brand.</h2></div><p>${p.partnerIntro}</p></div><div class="partner-models">${p.models.map(x=>`<div class="model-card"><span class="model-no">${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></div>`).join('')}</div></section><section class="dark-band"><div class="process"><div><div class="eyebrow">White-label by design</div><h2>Keep the client relationship. Extend the production team.</h2><p class="process-intro">Clear scopes, documented handoffs, confidentiality and a production culture built for repeat work.</p></div><div class="process-list"><div class="process-item"><span class="process-num">01</span><div><strong>Brief</strong><p>Your scope, specs and deadlines.</p></div><span class="process-arrow">↗</span></div><div class="process-item"><span class="process-num">02</span><div><strong>Build</strong><p>The right people and workflow.</p></div><span class="process-arrow">↗</span></div><div class="process-item"><span class="process-num">03</span><div><strong>Review</strong><p>QC and corrections before delivery.</p></div><span class="process-arrow">↗</span></div><div class="process-item"><span class="process-num">04</span><div><strong>Scale</strong><p>Recurring capacity when you need it.</p></div><span class="process-arrow">↗</span></div></div></div></section><section class="section compact"><div class="cta-panel"><div><h2>${p.cta}</h2><p>Let’s explore where ACX Media can strengthen your workflow.</p></div><a class="button" href="#contact" data-route="contact">${t('talk')} <span>↗</span></a></div></section></div>`; }
function about() { const p=c('about'); return `<div class="page">${pageHero(p,'06')}<section class="section"><div class="about-grid"><div><div class="eyebrow">${p.eyebrow}</div><p class="about-statement">${p.statement}</p></div><div class="about-copy"><p>${p.p1}</p><p>${p.p2}</p></div></div><div class="evolution"><span>VD</span><b>→</b><span>Accessibility</span><b>→</b><span>Audio</span><b>→</b><span>Localization</span><b>→</b><span>Dubbing</span><b>→</b><span>QC</span><b>→</b><span>Global production</span></div></section><section class="section compact"><div class="section-head"><div><div class="eyebrow">What guides us</div><h2>Small team energy. Serious production standards.</h2></div><p>We are building an agile company that combines studios, technology, human talent and documented workflows.</p></div><div class="values-grid">${p.values.map(x=>`<div class="value-card"><h3>${x[0]}</h3><p>${x[1]}</p></div>`).join('')}</div></section></div>`; }
function contact() { const p=c('contact'); return `<div class="page"><section class="contact-grid"><div class="contact-copy"><div class="eyebrow">${p.eyebrow}</div><h1>${p.title}</h1><p class="lead">${p.lead}</p><div class="contact-details">${p.details.map(x=>`<div class="contact-detail"><span>${x[0]}</span><span>${x[0].toLowerCase().includes('email') || x[0].toLowerCase().includes('e-mail') ? `<a href="mailto:${x[1]}">${x[1]}</a>` : x[1]}</span></div>`).join('')}</div></div><form class="contact-form" id="contactForm"><h2>${p.formTitle}</h2><div class="form-grid"><div class="field"><label>${p.labels[0]}</label><input required placeholder="${p.placeholders[0]}" /></div><div class="field"><label>${p.labels[1]}</label><input placeholder="${p.placeholders[1]}" /></div><div class="field"><label>${p.labels[2]}</label><input required type="email" placeholder="${p.placeholders[2]}" /></div><div class="field"><label>${p.labels[3]}</label><select required><option value="">${p.placeholders[3]}</option>${p.select.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field full"><label>${p.labels[4]}</label><textarea required placeholder="${p.placeholders[4]}"></textarea></div></div><div class="form-bottom"><p class="form-note">${p.formNote}</p><button class="button button-primary" type="submit">${t('start')} <span>↗</span></button></div></form></section></div>`; }

const templates = { home, services, industries, studios, languages, work, partners, about, contact };
function render() {
  const route = routeName();
  app.innerHTML = templates[route]();
  document.documentElement.lang = lang;
  document.title = route === 'home' ? 'ACX Media — Global Media Localization & Production' : `ACX Media — ${route[0].toUpperCase()+route.slice(1)}`;
  document.querySelectorAll('[data-route]').forEach(el => el.classList.toggle('active', el.dataset.route === route));
  document.querySelector('.main-nav').classList.remove('open');
  document.querySelector('.mobile-menu').setAttribute('aria-expanded','false');
  syncChrome();
  bindPageInteractions();
  window.scrollTo({top:0, behavior:'instant'});
}
function syncChrome() {
  const p = copy[lang];
  const nav = document.querySelectorAll('.main-nav a');
  p.nav.forEach((text,i)=>{ if(nav[i]) nav[i].textContent = text; });
  document.querySelector('.lang-en').classList.toggle('active', lang==='en');
  document.querySelector('.lang-fr').classList.toggle('active', lang==='fr');
  document.querySelectorAll('[data-i18n]').forEach(el=>{ if(p[el.dataset.i18n]) el.textContent = p[el.dataset.i18n]; });
  document.querySelector('.top-actions .button').innerHTML = `${p.start} <span>↗</span>`;
}
function bindPageInteractions() {
  const form = document.getElementById('contactForm');
  if(form) form.addEventListener('submit', e=>{ e.preventDefault(); showToast(lang==='fr' ? 'Merci — votre demande a bien été reçue.' : 'Thank you — your project details have been received.'); form.reset(); });
  document.querySelectorAll('[data-toast]').forEach(el=>el.addEventListener('click',()=>showToast(lang==='fr' ? 'Aperçu de démo bientôt disponible.' : el.dataset.toast)));
}
function showToast(message) { toast.textContent=message; toast.classList.add('show'); clearTimeout(window.__toast); window.__toast=setTimeout(()=>toast.classList.remove('show'),3500); }

document.querySelector('.lang-switch').addEventListener('click',()=>{ lang=lang==='en'?'fr':'en'; localStorage.setItem('acx-lang',lang); render(); });
document.querySelector('.mobile-menu').addEventListener('click',()=>{ const nav=document.querySelector('.main-nav'); nav.classList.toggle('open'); document.querySelector('.mobile-menu').setAttribute('aria-expanded', nav.classList.contains('open')); });
window.addEventListener('hashchange', render);
render();
